[package]
name = "upload"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
hyper = "0.14"
uuid = "1.0"
tokio-util = "0.6"

#reqwest = { version = "0.11", features = ["multipart"] }
#tokio = { version = "1", features = ["full"] }
